openapi: 3.1.0
info:
  version: 1.0.0
  title: Harmoniq project
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of harmoniq project
tags:
  - name: Auth
    description: Auth operations.
  - name: Articles
    description: Article operations.
servers:
  - url: http://localhost:3000
  - url: https://truestack.onrender.com
paths:
  /auth/register:
    post:
      $ref: ../swagger/paths/auth/register/post.yaml
  /auth/login:
    post:
      $ref: ../swagger/paths/auth/login/post.yaml
  /auth/logout:
    post:
      $ref: ../swagger/paths/auth/logout/post.yaml
  /auth/refresh:
    post:
      $ref: ../swagger/paths/auth/refresh/post.yaml
  /articles/{articleId}:
    get:
      $ref: ../swagger/paths/articles/{articleId}/get.yaml
    patch:
      $ref: ../swagger/paths/articles/{articleId}/patch.yaml
    delete:
      $ref: ../swagger/paths/articles/{articleId}/delete.yaml
  /articles:
    post:
      $ref: ../swagger/paths/articles/post.yaml
    get:
      $ref: ../swagger/paths/articles/get.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
